[theme]
primaryColor = "#2ca02c"  # Green, golf-inspired
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
# Limit uploads to 50MB to avoid Render request size errors
maxUploadSize = 50
